import { EUserRole, IPatient } from "../modules/avatarPopOverContent/interface";

export const patientData: IPatient[] = [
  {
    _id: "1p",
    name: "Ayush Verma",
    age: 30,
    profile_pic: "profilePic.jpeg",
    user_name: "ayush_verma",
    email: "ayushverma@gmail.com",
    contact_number: "+1(382)880-9067",
    address: "BHU, Windsor, Canada",
    role: "patient" as EUserRole,
    gender: "male",
    room_id: "1rp",
  },
  {
    _id: "2p",
    name: "Tom Cruise",
    age: 30,
    profile_pic: "patient_1.jpeg",
    user_name: "tom_cruise",
    email: "tomcruise@gmail.com",
    contact_number: "+1(382)880-3489",
    address: "EGH, Windsor, Canada",
    role: "patient" as EUserRole,
    gender: "male",
    room_id: "2rp",
  },
  {
    _id: "3p",
    name: "Kiya Johnson",
    age: 30,
    profile_pic: "patient_2.jpeg",
    user_name: "kiya_johnson",
    email: "kiyajohnson@gmail.com",
    contact_number: "+1(382)880-1234",
    address: "CJI, Windsor, Canada",
    role: "patient" as EUserRole,
    gender: "male",
    room_id: "3rp",
  },
];
