export const digicareConfig = {
  webPort: "http://localhost:3000/",
  showRealTimeDataImage: false,
  defaultReading: 0,
  days: [
    {
      value: "Sun",
      label: "Sunday",
    },
    {
      value: "Mon",
      label: "Monday",
    },
    {
      value: "Tue",
      label: "Tuesday",
    },
    {
      value: "Wed",
      label: "Wednesday",
    },
    {
      value: "Thu",
      label: "Thursday",
    },
    {
      value: "Fri",
      label: "Friday",
    },
    {
      value: "Sat",
      label: "Saturday",
    },
  ],
  specialization: [
    { label: "Internal medicine", value: "Internal medicine" },
    { label: "Pediatrics", value: "Pediatrics" },
    { label: "Family medicine", value: "Family medicine" },
    { label: "Anesthesiology", value: "Anesthesiology" },
    { label: "Emergency medicine", value: "Emergency medicine" },
    { label: "Surgery", value: "Surgery" },
    { label: "Psychiatry", value: "Psychiatry" },
    { label: "Dermatology", value: "Dermatology" },
    {
      label: "Obstetrics and gynaecology",
      value: "Obstetrics and gynaecology",
    },
    { label: "Neurology", value: "Neurology" },
    { label: "Physical therapy", value: "Physical therapy" },
    { label: "General surgery", value: "General surgery" },
    { label: "Ophthalmology", value: "Ophthalmology" },
    { label: "Urology", value: "Urology" },
    { label: "Cardiology", value: "Cardiology" },
    { label: "Nuclear medicine", value: "Nuclear medicine" },
    { label: "Plastic surgery", value: "Plastic surgery" },
    { label: "Otorhinolaryngology", value: "Otorhinolaryngology" },
    { label: "Geriatrics", value: "Geriatrics" },
    { label: "Immunology", value: "Immunology" },
    { label: "Gastroenterology", value: "Gastroenterology" },
    { label: "Orthopedics", value: "Orthopedics" },
    { label: "Nephrology", value: "Nephrology" },
    { label: "Radiology", value: "Radiology" },
    { label: "Pathology", value: "Pathology" },
    { label: "Neurosurgery", value: "Neurosurgery" },
    { label: "Medical genetics", value: "Medical genetics" },
    { label: "Rheumatology", value: "Rheumatology" },
    { label: "Endocrinology", value: "Endocrinology" },
    { label: "Occupational medicine", value: "Occupational medicine" },
    { label: "Oncology", value: "Oncology" },
    { label: "Cardiothoracic surgery", value: "Cardiothoracic surgery" },
    { label: "Hospital medicine", value: "Hospital medicine" },
    { label: "Diagnostic Radiology", value: "Diagnostic Radiology" },
    { label: "Intensive care medicine", value: "Intensive care medicine" },
    { label: "Hematology", value: "Hematology" },
    { label: "Preventive healthcare", value: "Preventive healthcare" },
    { label: "Pulmonology", value: "Pulmonology" },
    {
      label: "Physical medicine and rehabilitation",
      value: "Physical medicine and rehabilitation",
    },
    { label: "Forensic pathology", value: "Forensic pathology" },
    { label: "Biochemistry", value: "Biochemistry" },
    { label: "Sports medicine", value: "Sports medicine" },
    { label: "Vascular surgery", value: "Vascular surgery" },
    { label: "Anatomical pathology", value: "Anatomical pathology" },
    { label: "Interventional radiology", value: "Interventional radiology" },
    {
      label: "Spinal Cord Injury Medicine",
      value: "Spinal Cord Injury Medicine",
    },
    { label: "Neuroradiology", value: "Neuroradiology" },
    { label: "Clinical pathology", value: "Clinical pathology" },
    { label: "Pain management", value: "Pain management" },
    { label: "Public health", value: "Public health" },
    { label: "Brain Injury Medicine", value: "Brain Injury Medicine" },
  ],
  study_history: [
    { label: "MBBS", value: "MBBS" },
    { label: "BMBS", value: "BMBS" },
    { label: "MBChC", value: "MBChC" },
    { label: "MBChB", value: "MBChB" },
    { label: "MBBCh", value: "MBBCh" },
    { label: "MB", value: "MB" },
    { label: "BM", value: "BM" },
    { label: "BMed", value: "BMed" },
    { label: "MBBS", value: "MBBS" },
    { label: "BMBS", value: "BMBS" },
    { label: "MBChC", value: "MBChC" },
    { label: "MBBCh", value: "MBBCh" },
    { label: "MD", value: "MD" },
    { label: "DO", value: "DO" },
  ],
  editableUserKeys: [
    "DOB",
    "address",
    "contact_number",
    "email",
    "specialization",
    "study_history",
    "Hospital",
  ],
  userKeysToShow: [
    "DOB",
    "address",
    "contact_number",
    "email",
    "user_name",
    "gender",
    "specialization",
    "study_history",
    "Hospital",
  ],
  realtimeUnits: {
    o2: { unit: "%", min: "90", max: "100" },
    blood_pressure: { unit: "mmHg", min: "90/60", max: "120/80" },
    sugar_level: { unit: "mg/dL", min: "70", max: "125" },
    heart_rate: { unit: "bpm", min: "60", max: "100" },
  },
};
